trigger: 
  branches:
    include:
      - main
  paths:
    include:
      - .azurepipelines/inspec.yaml
      - inspec/*

schedules:
  - cron: "0 8,16 * * *"
    displayName: Daily build
    branches:
      include:
        - main

resources:
  pipelines:
    - pipeline: chef
      source: qbikez.pi-chef
      trigger: true
        
      


pool: pi

stages:
  - stage: inspec
    jobs:
      - job:
        steps:
          - script: |
              # prepare env variables
              eval "$(rbenv init -)"
              rbenv sudo inspec exec inspec/pi_spec.rb